-- Generated by hypr2lua-web.

hl.config({
  general = {
    col = {
      active_border = {
        colors = { "rgba(0c0b0cee)", "rgba(e2dddcee)" },
      },
    },
    border_size = 2,
    gaps_in = 3,
    gaps_out = 4,
  },
  group = {
    col = {
      border_active = "rgba(e2dddcee)",
      border_inactive = "rgb(0c0b0c)",
    },
    groupbar = {
      col = {
        active = "rgba(c38b7b99)",
        inactive = "rgba(584e5188)",
      },
      text_color = "rgb(FAFCFB)",
      text_color_inactive = "rgba(FAFCFBee)",
    },
  },
  decoration = {
    rounding = 3,
    rounding_power = 3,
    shadow = {
      enabled = true,
      render_power = 3,
      range = 16,
      color = "rgba(00000052)",
    },
  },
})

hl.window_rule({
  opacity = "1.0 override",
  no_dim = true,
  match = {
    class = "^(vesktop|Vesktop)$",
  },
})
hl.window_rule({
  opacity = "1.0 override",
  no_dim = true,
  match = {
    class = "^(code|VSCode|VSCodium)$",
  },
})
hl.window_rule({
  opacity = "1.0 override",
  no_dim = true,
  match = {
    class = "^(chromium|Chromium|google-chrome|Brave|brave-browser)$",
  },
})
