-- Generated by scripts/hypr2lua.
-- Source: /home/hancore/.config/omarchy/themes/saga/hyprland.conf

-- A uniform, subtle focus border at 20% white.
local active_border_color = "rgba(ffffff33)"

hl.config({
  general = {
    col = {
      active_border = active_border_color,
      inactive_border = "rgb(05080a)",
    },
    gaps_in = 4,
    gaps_out = 8,
    border_size = 2,
  },
  group = {
    col = {
      border_active = active_border_color,
      border_inactive = "rgb(141719)",
    },
  },
  decoration = {
    rounding = 5,
    rounding_power = 4,
    blur = {
      enabled = true,
      size = 12,
      passes = 3,
      ignore_opacity = true,
      new_optimizations = true,
      xray = false,
      noise = 0.02,
      contrast = 0.92,
      brightness = 0.82,
      vibrancy = 0.20,
      vibrancy_darkness = 0.15,
    },
    shadow = {
      enabled = true,
      render_power = 6,
      range = 20,
      color = "rgba(05080a99)",
    },
  },
  animations = {
    enabled = true,
  },
})

-- Blur only the Quickshell Omarchy Menu surface. The low alpha cutoff keeps
-- the transparent full-screen scrim clear while blurring the menu card.
hl.layer_rule({
  name = "lasthorizon-omarchy-menu",
  match = { namespace = "^omarchy-menu$" },
  blur = true,
  ignore_alpha = 0.10,
  xray = false,
})

-- This theme keeps application windows fully opaque, including when unfocused.
o.window(".*", { opacity = "1 override 1 override 1 override" })

-- A lone tiled window does not need a focus indicator.
hl.window_rule({
  match = { float = false, workspace = "w[tv1]" },
  border_size = 0,
})

hl.curve("expressiveFastSpatial", { type = "bezier", points = { { 0.42, 1.67 }, { 0.21, 0.90 } } })
hl.curve("expressiveSlowSpatial", { type = "bezier", points = { { 0.39, 1.29 }, { 0.35, 0.98 } } })
hl.curve("expressiveDefaultSpatial", { type = "bezier", points = { { 0.38, 1.21 }, { 0.22, 1.00 } } })
hl.curve("emphasizedDecel", { type = "bezier", points = { { 0.05, 0.7 }, { 0.1, 1 } } })
hl.curve("emphasizedAccel", { type = "bezier", points = { { 0.3, 0 }, { 0.8, 0.15 } } })
hl.curve("standardDecel", { type = "bezier", points = { { 0, 0 }, { 0, 1 } } })
hl.curve("menu_decel", { type = "bezier", points = { { 0.1, 1 }, { 0, 1 } } })
hl.curve("menu_accel", { type = "bezier", points = { { 0.52, 0.03 }, { 0.72, 0.08 } } })

hl.animation({
  leaf = "windowsIn",
  enabled = true,
  speed = 3,
  bezier = "emphasizedDecel",
  style = "popin 80%",
})
hl.animation({
  leaf = "windowsOut",
  enabled = true,
  speed = 2,
  bezier = "emphasizedDecel",
  style = "popin 90%",
})
hl.animation({
  leaf = "windowsMove",
  enabled = true,
  speed = 3,
  bezier = "emphasizedDecel",
  style = "slide",
})
hl.animation({
  leaf = "border",
  enabled = false,
})
hl.animation({
  leaf = "layersIn",
  enabled = true,
  speed = 2.7,
  bezier = "emphasizedDecel",
  style = "popin 93%",
})
hl.animation({
  leaf = "layersOut",
  enabled = true,
  speed = 2.4,
  bezier = "menu_accel",
  style = "popin 94%",
})
hl.animation({
  leaf = "fadeLayersIn",
  enabled = true,
  speed = 0.5,
  bezier = "menu_decel",
})
hl.animation({
  leaf = "fadeLayersOut",
  enabled = true,
  speed = 2.7,
  bezier = "menu_accel",
})
hl.animation({
  leaf = "workspaces",
  enabled = true,
  speed = 7,
  bezier = "menu_decel",
  style = "slide",
})
hl.animation({
  leaf = "specialWorkspaceIn",
  enabled = true,
  speed = 2.8,
  bezier = "emphasizedDecel",
  style = "slidevert",
})
hl.animation({
  leaf = "specialWorkspaceOut",
  enabled = true,
  speed = 1.2,
  bezier = "emphasizedAccel",
  style = "slidevert",
})
